apiVersion: v1
kind: Service
metadata:
  name: fooocus-service
  namespace: {{ .Values.namespace }}
  labels:
    owner: devops
    instanceType: gpu
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7865
      protocol: TCP
      targetPort: 7865
  selector:
    app: fooocus